### ISSUE TITLE
还有很多地方没翻译，什么时候出更新啊

### ISSUE THREAD

**Issue by weborld** [cubacn/translation-cn#2]
还有很多地方没翻译，什么时候出更新啊

**Comment by BryanYin** [comment]
@weborld 有截图吗？

**Comment by weborld** [comment]
设置界面的caption是英文的，用户组里面一大堆都是英文的。

**Comment by weborld** [comment]
![1](https://user-images.githubusercontent.com/5875289/56265363-ea094c80-611b-11e9-9f6b-199623b7f2df.png)

**Comment by BryanYin** [comment]
谢谢，我们也发现了不少，是因为7.0有新的设置官方还没有加进来。月末会推出一版升级，基本能修复大部分的界面翻译问题。

**Comment by weborld** [comment]
另外扩展默认的界面比如User.Browse，会出现一些地方汉化丢失的问题

**Comment by 7polo** [comment]
工作流相关的也存在没有汉化的问题
