### ISSUE TITLE
编辑窗口的取消按钮汉化有问题，应为“关闭”

### ISSUE THREAD

**Issue by weborld** [cubacn/translation-cn#8]
默认的编辑界面上有两个按钮对应是windowCommitAndClose和windowClose两个action。中文版这个地方windowClose汉化有点问题，取消的意思一般理解为关闭且不保存，而实际对应的功能其实是关闭窗口（会提示是否保存），所以这个地方翻译为关闭更准确!

**Comment by BryanYin** [comment]
`    <layout>
        <hbox spacing="true" stylename="c-edit-window-actions">
            <button id="windowCommit" action="windowCommit" icon="EDITOR_OK"/>
            <button id="windowClose" action="windowClose" icon="EDITOR_CANCEL"/>
        </hbox>
    </layout>
`
这里用的 EDITOR_CANCEL icon，所以还是用“取消”作为翻译。取消确实有关闭且不保存的意思，不过用在这里差别不大，因为后面还会有弹窗询问是否保存。

**Comment by weborld** [comment]
就是因为这个地方用户点了之后会提示是否保存，如果是“取消”的话，用户已经明确了不需要保存了，再提示就没必要了。改成“关闭”后，再来提示是否保存或者取消，就比较符合操作习惯。至少在中国的软件操作习惯都是这样的。如果你们觉得这个地方官方不改的话，请问我如何自己把这地方全局改掉呢？谢谢
